---
title: "discussion things to be added"
output: html_notebook
---

In this study we have shown that education does indeed have an effect on total fertility rates, in that as the percentage of females enrolled in secondary education (FESE) increases so the total fertility rate (TFR) decreases. This is true at both a global level as well as a country specific level as was demonstrated. However, as can be seen in figure one and two the strength of the relationship between the two variables, FESE and TFR differ. This is to be expected as the global data includes a wider range whereas at a country level populations are much smaller. Nevertheless the degree of correlation is still highly profound. 
In 2014, Manoel Bittencourt of the University of Pretoria conducted a similar study. He however made use of primary school completion instead. Nonetheless our results are on par with that of his study, in that they display a relationship in which education can lower fertility rates. Furthermore these findings are important in that lower fertility rates as a result of a more educated population, leads to an increase in capital per wage earner resulting in increased productivity and subsequently increased growth rates (Bittencourt, 2014). In the case of underdeveloped countries, this means that the country has the ability to shift from a state in which the population increases at a faster rate than its means of subsistence to a more sustained growth system.
A sustainable growth system does sound appealing but how can one enforce the attainment of education? Consider the case of the Kenyan educational reform of 1985 where the government added an extra year before being suitable to earn the certificate of primary education. With Kenya’s independence from colonialism, came the need for an educational reform mainly due to the fact that prior to its independence the Kenyan education system was extremely basic and lacked substantial content that promotes widespread sustainable employment (Wanjohi, 2011). In 2012, Chicoine conducted a study targeting data collected during the time of this reform as well as post reform data in which he tested its effect on fertility rates. Much like Bittencourt as well as the results related to the present study, he concluded that as a result of an additional one year to primary education, a significant decrease in total fertility rate was observed as a result of postponed marriage and sexual activity, hence increased schooling can have a positive effect on choices and decision making of young women. Indicating the validity of this method in terms of a solution in mitigate an increasing population size. 

