---
title: intro and outro
output: thingamabobs
---

The growth of global population size has brought about unprecedented changes to our natural environment. This exponential increase warrants the need to mitigate population size in order to keep the many ecosystem services that species working together provide. For instance as humans we rely on certain plants and animals as biological resources. They provide foundational material for the production of medication, food, pharmaceutical materials as well as raw materials wood and cotton used for the production of clothing, furniture and paper among others. All these aforementioned natural goods work in synchronicity to increase human health and well-being.
On the other hand we have ecosystem services, many of which have profound effects on life. In that life cannot persist without its aid (oxygen provided to us by plants and phytoplankton). Due to the complexity of plant and animal interactions a complex food web exists which allows for the maintenance of balance among organisms. The production of oxygen as a by-product of photosynthesis as well as the extraction of carbon dioxide from the atmosphere by plants is one of the most if not the most important service ecosystems provide. Insects also play a huge role in the pollination of plant species allowing for the great diversity of plant life. To some extent vegetation also has a role to play with maintaining microclimates around the world which in turn provide specific niches for organisms. All these aforementioned ecosystem goods and services contribute to global biological diversity. This now is under serious threat due to human impact on the natural environment.
The industrial revolution gave rise to an era of highly advanced technologies which brought about the over extraction of natural resources. The advancement of modern technology is partly being driven by the need to keep up with global population increases. As we know when population increases so does the need for more infrastructures such as roads, water lines, electric lines, housing as well as agricultural cultivation become more prevalent. This entire means is that more space needs to be acquired and in doing so more of the natural environment becomes altered. The housing development in the Philippi Horticultural Area (PHA) provides a perfect example. The PHA is an agricultural hub in close proximity of the city centre and provides Cape Town distributors with roughly 60% of its fresh produce. The PHA is unique in that there exit only a few examples such as this around the world (agricultural hub close to city centre). Due to an increase in housing demand by low income citizen’s developers together with the city aimed to develop low to medium income housing on prime agricultural land as well as prime underground recharge land. This move to develop on prime underground recharge land at the peak of a drought appears to be quite reckless and it was made known that developers cut corners when commencing with the environmental impact assessment. Nazeer Sonday an active citizen of the PHA has been battling developers for just shy of a decade now and in doing so has brought to light the importance of the area natural as well as economically.
Such developments are driven by the need for housing by citizens due to a rise in population size. This can be tied into the relationship between fertility (number of offspring per household) and education enrolment rates, in that the more educated the general population becomes so the fertility rate decreases putting less pressure on the need for housing development and simultaneously increasing standard of living.(IF YOU HAVE A STUDY THAT SHOWS STANARD OF LIVING INCREASES AS A RESULT OF A MORE EDUCATED GENERAL POPULATION THAT WOULD BE GREAT).



